import { GoogleGenAI } from "@google/genai";
import env from "../config/env.js";
import logger from "../config/logger.js";
import { InterviewError } from "../utils/interviewError.js";
import { reportSchema, resumeSchema } from "../schemas/interviewReport.js";

const AI_MODEL = "gemini-2.5-flash";

const ai = new GoogleGenAI({
  apiKey: env.GEMINI_API_KEY,
});

/**
 * @name generateInterviewReportAI
 * @description Service for generating interview report based on resume, selfDescription and jobDescription using AI service
 * @param {resume, selfDescription, jobDescription}
 * @access private
 */
export async function generateInterviewReportAI({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
Analyze the candidate resume, self description and job description.

Generate an interview preparation report.

The "report" field should contain a detailed Markdown report with sections:
## Candidate Summary
## Match Score Explanation
## Suggested Improvements


Candidate Data:

Resume:
${resume}

Self Description:
${selfDescription}

Job Description:
${jobDescription}
`;

  try {
    const response = await ai.models.generateContent({
      model: AI_MODEL,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: reportSchema,
      },
    });

    const result = JSON.parse(response.text);
    logger.info("AI RESULT:", result);

    return result;
  } catch (e) {
    logger.error("AI Generation Error: ", e);
    throw new InterviewError(e.message, 400);
  }
}

/**
 * @name generateResumeAI
 * @description Service for generating resume based on resume, selfDescription and jobDescription using AI service
 * @access private
 */
export async function generateResumeAI({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;
  try {
    logger.info("GENERATIG AI RESUME", { selfDescription, jobDescription });
    const res = await ai.models.generateContent({
      model: AI_MODEL,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: resumeSchema,
      },
    });

    const result = JSON.parse(res.text);
    logger.info("RESUME_PDF_CONTENT", result);

    return result;
  } catch (e) {
    logger.error("AI Resume Generation Error:", e);
    throw new InterviewError(e.message, 400);
  }
}
